services:
  postgres:
    image: postgres:16
    container_name: crypto-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: crypto
    ports:
      - "5432:5432"
    volumes:
      - crypto-data:/var/lib/postgresql/data

volumes:
  crypto-data: